### ISSUE TITLE
スクレイピングスクリプト作成

### ISSUE THREAD

**Issue by jimako1989** [plamo-guide/plamo-guide#1]
## 背景
現状は手入力のデータを用いているため，本システムのスケールアップに時間と労力がかかり，現実的でない

## 対応
メーカの一覧サイトは規則的なアドレスになっているので，スクレイピングスクリプトの作成を検討する．
DBのミドルウェアも為念確認する．（規模や信頼性としてもsqlite3よりもMySQLあたりか？）

 1. 対応するメーカーサイトの規則性を把握し，取得できる詳細仕様の検討
 1. テーブル定義の検討
 1. スクレイピングスクリプトを作成し，稼働
... 定期的に更新する必要があるか確認する．定期稼働が必要な場合，稼働サーバの検討を行う必要あり

**Comment by jimako1989** [comment]
@tanaka-hiroki1989 詳細（メーカサイトURL，カタログ番号の規則性，項目，型等）が決まりましたら連携お願いします:bow:

**Comment by tanaka-hiroki1989** [comment]
まずは, 下記から試していただけますでしょうか？
- [ ] タミヤ製飛行機モデル（一部のシリーズとシリーズ外商品を除く）
  - URL：https://www.tamiya.com/japan/products/<商品番号>/index.html
  - 対象商品：商品番号が下記のもの
    - 60302〜61013（1/32 エアークラフトシリーズ）
    - 61013〜61118  （1/48傑作機シリーズ）
    - 61601〜61610 （1/100 コンバットプレーンシリーズ）
    - 60701〜60789（1/72 ウォーバードコレクション）
  - 項目（例は https://www.tamiya.com/japan/products/61013/index.html の場合）
    - 商品番号（例：61013）→VARCHAR型10文字
    - シリーズ名（例：1/48 傑作機シリーズ）→ VARCHAR型40文字
    - シリーズ内番号（例：13）→VARCHAR型4文字
    - 商品名（例：1/48 陸軍四式戦闘機 疾風）→ VARCHAR型60文字
    - 税込価格（例：1620）→MEDIUMINT型
    - 本体価格（例：1500）→MEDIUMINT型
    - TAMIYA SHOP ONLINEへのリンク（例：http://tamiyashop.jp/shop/g/g61013/）→VARCHAR型100文字

【注意点】
- TAMIYA SHOP ONLINEへのリンクが存在しない商品があります（生産休止の場合など）
- 通販サイトのTAMIYA SHOP ONLINEでも同様の情報が取得できそうですが、まずは公式サイトからの情報取得をお願いします。

**Comment by tanaka-hiroki1989** [comment]
@jimako1989 スクレイピングスクリプトはこれから順次増やしていくことになると思うので、都度issueを立てていくということで問題ないでしょうか？

**Comment by jimako1989** [comment]
そうですね。DB冗長化など考えるべきことはクリアし、動作が安定してきたら、単発PRレビューで変更箇所の相互レビューなどで機動的に対処しましょう。
