### ISSUE TITLE
アプリサイト公開

### ISSUE THREAD

**Issue by jimako1989** [plamo-guide/plamo-guide#2]
## 背景
現状はどこにも公開されていないのでローカルに落としてきて挙動を確認する必要があるが，これだと挙動が確認しにくい．いずれ公開するのだから，後回しにせずアジャイル開発(develop->commit->deploy->check)のサイクルは小さくしたい．

## 対応
VCSはGithub上の本レポジトリで良いとして，デプロイはherokuが有名か．下記に従えばとりあえずRubyOnRailsアプリをする事が公開することができると思われる．

railsで作ったアプリをとりあえず公開する方法。rails＋GitHub(GitHub Desktop)＋heroku
https://qiita.com/Kohei_Kishimoto0214/items/d4a4ca13d4a8ab11b3f8

**Comment by tanaka-hiroki1989** [comment]
@jimako1989 
ドメインは.comが妥当でしょうかね。ところで、本番環境とテスト環境をわけませんか？

**Comment by jimako1989** [comment]
> @jimako1989
> ドメインは.comが妥当でしょうかね。ところで、本番環境とテスト環境をわけませんか？

#4 起票しました．検討お願いします．少し先の段階かなと思います．

**Comment by tanaka-hiroki1989** [comment]
@jimako1989 welcomeページへのroutingを設定し, 表示されることを確認できましたら, 本件クローズとさせてください。後ほどプルリクエストを送ります。

**Comment by tanaka-hiroki1989** [comment]
@jimako1989 ↑のコメントは理解不足で、welocomeページへのroutingは設定済みでした。本件クローズとします。

**Comment by jimako1989** [comment]
@tanaka-hiroki1989 
今のmaster，エラーみたいだけどdevelop→masterにリリースしていい？
https://plamo-guide.herokuapp.com/

**Comment by tanaka-hiroki1989** [comment]
@jimako1989 OKです、リリースしましょう
