### ISSUE TITLE
slim導入

### ISSUE THREAD

**Issue by tanaka-hiroki1989** [plamo-guide/plamo-guide#39]
テンプレートエンジンとしてhamlを採用する方針でしたが、変更してslimを採用したいと思います。

hamlより記述が簡潔となり、より高速です.
アプリ開発担当者はhamlには習熟していますがslimは未経験のため新たな技術獲得につながると考えています.

**Comment by jimako1989** [comment]
@tanaka-hiroki1989 こちらのIssueはクローズでしょうか？
